version: "3"

services:
  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jbook
    networks:
      - jbook-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "5050:80"
      networks:
        - jbook-network
      depends_on:
        - db

  migrations:
    build:
      context: ./
      dockerfile: ./Docker-migrations
      args:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "jbook"
        POSTGRES_HOST: "db"
        POSTGRES_PORT: "5432"
    container_name: alembic-migrations
    command: alembic upgrade head
    networks:
      - jbook-network
    links:
      - db:db
    depends_on:
      - db

  web:
    build: ./
    container_name: fastapi
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jbook
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 8008:8000
    networks:
      - jbook-network
    links:
      - db:db
    depends_on:
      - db
      - migrations


networks:
  jbook-network:
    driver: bridge
    external: false

volumes:
  postgres-data: