version: '3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - jbook-network
    depends_on:
      - db
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db/jbook"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - jbook-network
    links:
      - db:db
  db:
    image: postgres:13-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jbook
    networks:
      - jbook-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  jbook-network:
    driver: bridge
    external: false

volumes:
  postgres-data:
