"""minor changes

Revision ID: 4be24e530149
Revises: eae8b9ac4103
Create Date: 2021-12-18 10:15:31.736282

"""
from alembic import op
import sqlalchemy as sa


revision = '4be24e530149'
down_revision = 'eae8b9ac4103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_comment', sa.Column('pub_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True), schema='jbook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_comment', 'pub_date', schema='jbook')
    # ### end Alembic commands ###
