"""rated at field added

Revision ID: 77e4654db65b
Revises: d8162b9a92dd
Create Date: 2021-12-21 17:18:10.506802

"""
from alembic import op
import sqlalchemy as sa


revision = '77e4654db65b'
down_revision = 'd8162b9a92dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_rate', sa.Column('rated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True), schema='jbook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_rate', 'rated_at', schema='jbook')
    # ### end Alembic commands ###
