"""shelf comment

Revision ID: 99af38bd32a8
Revises: 77e4654db65b
Create Date: 2021-12-21 23:36:41.606917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '99af38bd32a8'
down_revision = '77e4654db65b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shelf_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pub_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shelf_uid'], ['jbook.shelf.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['jbook.user.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='jbook'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_comment', schema='jbook')
    # ### end Alembic commands ###
