"""user.uid

Revision ID: ad6fbc6cfebe
Revises: 4be24e530149
Create Date: 2021-12-20 05:53:39.194578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ad6fbc6cfebe'
down_revision = '4be24e530149'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('book_rate_user_id_fkey', 'book_rate', schema='jbook', type_='foreignkey')
    op.drop_constraint('shelf_user_id_fkey', 'shelf', schema='jbook', type_='foreignkey')
    op.drop_constraint('book_comment_user_id_fkey', 'book_comment', schema='jbook', type_='foreignkey')
    op.drop_constraint('user_username_key', 'user', schema='jbook', type_='unique')
    op.drop_constraint('shelf_rate_user_id_fkey', 'shelf_rate', schema='jbook', type_='foreignkey')

    op.execute('DELETE FROM jbook.user;')
    op.add_column('user', sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False), schema='jbook')
    op.create_unique_constraint('user_uid_key', 'user', ['uid'], schema='jbook')
    op.drop_column('user', 'id', schema='jbook')
    op.drop_column('user', 'status', schema='jbook')
    op.drop_column('user', 'username', schema='jbook')

    op.add_column('book_comment', sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=True), schema='jbook')
    op.create_foreign_key(None, 'book_comment', 'user', ['user_uid'], ['uid'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('book_comment', 'user_id', schema='jbook')
    op.add_column('book_rate', sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=True), schema='jbook')
    op.create_foreign_key(None, 'book_rate', 'user', ['user_uid'], ['uid'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('book_rate', 'user_id', schema='jbook')
    op.add_column('shelf', sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=True), schema='jbook')
    op.create_foreign_key(None, 'shelf', 'user', ['user_uid'], ['uid'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('shelf', 'user_id', schema='jbook')
    op.add_column('shelf_rate', sa.Column('user_uid', postgresql.UUID(as_uuid=True), nullable=False), schema='jbook')
    op.create_foreign_key(None, 'shelf_rate', 'user', ['user_uid'], ['uid'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('shelf_rate', 'user_id', schema='jbook')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.VARCHAR(length=25), autoincrement=False, nullable=True), schema='jbook')
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='jbook')
    op.add_column('user', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('jbook.user_id_seq'::regclass)"), autoincrement=True, nullable=False), schema='jbook')
    op.create_unique_constraint('user_username_key', 'user', ['username'], schema='jbook')
    op.drop_column('user', 'uid', schema='jbook')
    op.add_column('shelf_rate', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='jbook')
    op.drop_constraint(None, 'shelf_rate', schema='jbook', type_='foreignkey')
    op.create_foreign_key('shelf_rate_user_id_fkey', 'shelf_rate', 'user', ['user_id'], ['id'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('shelf_rate', 'user_uid', schema='jbook')
    op.add_column('shelf', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='jbook')
    op.drop_constraint(None, 'shelf', schema='jbook', type_='foreignkey')
    op.create_foreign_key('shelf_user_id_fkey', 'shelf', 'user', ['user_id'], ['id'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('shelf', 'user_uid', schema='jbook')
    op.add_column('book_rate', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='jbook')
    op.drop_constraint(None, 'book_rate', schema='jbook', type_='foreignkey')
    op.create_foreign_key('book_rate_user_id_fkey', 'book_rate', 'user', ['user_id'], ['id'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('book_rate', 'user_uid', schema='jbook')
    op.add_column('book_comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='jbook')
    op.drop_constraint(None, 'book_comment', schema='jbook', type_='foreignkey')
    op.create_foreign_key('book_comment_user_id_fkey', 'book_comment', 'user', ['user_id'], ['id'], source_schema='jbook', referent_schema='jbook')
    op.drop_column('book_comment', 'user_uid', schema='jbook')
    # ### end Alembic commands ###
