"""init migration

Revision ID: eae8b9ac4103
Revises: 50a2c9afdc87
Create Date: 2021-12-18 06:09:09.532630

"""
from alembic import op
import sqlalchemy as sa


revision = 'eae8b9ac4103'
down_revision = '50a2c9afdc87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'book', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_author', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_category', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_comment', ['id'], schema='jbook')
    op.add_column('book_image', sa.Column('book_id', sa.Integer(), nullable=True), schema='jbook')
    op.create_unique_constraint(None, 'book_image', ['id'], schema='jbook')
    op.create_foreign_key(None, 'book_image', 'book', ['book_id'], ['id'], source_schema='jbook', referent_schema='jbook')
    op.create_unique_constraint(None, 'book_in_shelf_tag', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_publisher', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_rate', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'book_tag', ['name'], schema='jbook')
    op.create_unique_constraint(None, 'shelf_image', ['id'], schema='jbook')
    op.create_unique_constraint(None, 'shelf_tag', ['name'], schema='jbook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelf_tag', schema='jbook', type_='unique')
    op.drop_constraint(None, 'shelf_image', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_tag', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_rate', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_publisher', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_in_shelf_tag', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_image', schema='jbook', type_='foreignkey')
    op.drop_constraint(None, 'book_image', schema='jbook', type_='unique')
    op.drop_column('book_image', 'book_id', schema='jbook')
    op.drop_constraint(None, 'book_comment', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_category', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book_author', schema='jbook', type_='unique')
    op.drop_constraint(None, 'book', schema='jbook', type_='unique')
    # ### end Alembic commands ###
