"""initial

Revision ID: 6cb86f653b67
Revises: 
Create Date: 2021-11-07 20:47:26.303078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb86f653b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('book_author',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('author_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('book_category',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('category_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('publishing_house',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('publisher_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('book_id_seq')"), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishing_house.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('_m2m_book_book_author',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_author'], ['book_author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'book_author')
    )
    op.create_table('_m2m_book_book_category',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['book_category.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_m2m_book_book_category')
    op.drop_table('_m2m_book_book_author')
    op.drop_table('book')
    op.drop_table('publishing_house')
    op.drop_table('book_category')
    op.drop_table('book_author')
    # ### end Alembic commands ###
